repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        args: [--line-length=79]
        language_version: python3.12
        types: [python]
        exclude: ^(?:alembic|__pycache__|.venv|docker|\.git)/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        types: [python]
        args: ["--profile", "black", "--filter-files"]
        exclude: ^(?:alembic|__pycache__|.venv|docker|\.git)/

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          ["--max-line-length=79", "--extend-ignore=E266,F401"]
        types: [python]
        exclude: ^(?:alembic|__pycache__|.venv|docker|\.git)/
