"""edit books table

Revision ID: 72c748f3e1a0
Revises: 4a01ece5f63a
Create Date: 2025-05-18 14:41:59.112085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72c748f3e1a0"
down_revision: Union[str, None] = "4a01ece5f63a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books", "publication_year", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books", "publication_year", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
